### ISSUE TITLE
Python Error while using WalkingTime

### ISSUE THREAD

**Issue by Jan050881** [SrNetoChan/WalkingTime#3]
When i try to run the WalkingTime plugin a Python Error occurs after filling in the data and press the ok button. I'm not sure if this is a problem with the plugin or my Python console itself, but i hope someone has an idea. The error occurs even if i change layers, i tried it with different datasets, but no one works. Here is the error message:

Fehler bei der Ausführung von Python-Code:

Traceback (most recent call last):
  File "C:/Users/Jan/.qgis2/python/plugins\walkingtime\walkingtime.py", line 134, in run
    time, time_rev = self.timeCalc(geom)
  File "C:/Users/Jan/.qgis2/python/plugins\walkingtime\walkingtime.py", line 173, in timeCalc
    dh = elevation - last_elevation
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

Python-Version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS-Version:
2.2.0-Valmiera Valmiera, c3a2817

Thanks for your help!
Jan

**Comment by henkth** [comment]
Thank you for the WalkingTime plugin. Till date I have not been able to get it working. First I got the above listed Python problem, but after using the same CRS for project and layers, I am getting only 0.00 times for the columns time and rev_time. Would it be possible for you to send me a QGIS sample file that worked for you with some testing data so I can compare?
Thanks!

**Comment by SrNetoChan** [comment]
I won't be able to do that in the next hours (if not days). Can you send me a sample of your data instead? I will give it a look.

**Comment by henkth** [comment]
Dear Alexandro,

Thank you very much for the offer to look at the data. Please find them
included in a zip file with this mail. The area is around Leh in the Indian
Himalaya, projected in WGS 84 / UTM zone 43N.
I am using QGIS 2.8.2 on an iMac with OSX10.10.3

Best regards,

Henk Thoma

**Comment by SrNetoChan** [comment]
Can't see any attachement. Can you please send it to senhor.neto@gmail.com?

Thanks

**Comment by SrNetoChan** [comment]
Thank you for sending the sample. It did not work for me either. I will need some time to check/fix this.

**Comment by kgeographer** [comment]
Hello,
I am having the problem of "TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'" reported above. I am using QGIS v3 and the ported plug-in. The raster is a GMTED2010 tiff grid. I have tried both native WGS84 and reprojected to EPSG:54002. 

I also tried creating a degree slope surface from that and using it as the raster input, and it _did_ compute costs. But I don't think those values are meaningful. Are there any answers to come of this thread from 2 years ago?

thanks

**Comment by SrNetoChan** [comment]
@kgeographer what is the EPSG of your line layer?

**Comment by kgeographer** [comment]
I think the CRSes of the two layers were not set properly; everything was 4326 natively, and some had only been reprojected on loading. I have tried now a few things and the result is no more errors, but I get only zero values computed for time and rev_time. I ensured both lines and DEM are the same projection (epsg:54030 - Robinson), set all 'no data' to 0.
